name: Deploy to Ubuntu

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out repository
        uses: actions/checkout@v3

      
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.HAWOOND_HOME_SERVER }}

      
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOT'
            cd /var/www/deverse
            
            git pull origin production

            npm install

            npm run build

            pm2 stop deverse || true
            pm2 start build/index.js --name deverse
          EOT